# Generated by Django 4.2.7 on 2025-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Nacional", "Nacional"),
                            ("Internacional", "Internacional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
